edition: 1.0.0
name: tiktoka-download
access: default

vars:
  region: cn-hangzhou
  memorySize: 2048
  service:
    name: tiktoka-download
    description: '快速部署tiktoka-download 项目地址 https://github.com/duolabmeng6/paddlehub_ppocr'

services:
  framework:
    component: fc
    props:
      region: ${vars.region}
      service:
        name: ${vars.service.name}
        description: ${vars.service.description}
        internetAccess: true
        role:
          name: paddleocrrole
          policies:
            - AliyunContainerRegistryReadOnlyAccess
      function:
        name: tiktoka-download
        description: ${vars.service.description}
        runtime: custom-container
        memorySize: ${vars.memorySize}
        caPort: 5001
        codeUri: ./
        timeout: 60
        customContainerConfig:
          image: registry.cn-hangzhou.aliyuncs.com/tiktoka/tiktokadownload:1.0
#           command: '["sh","/PaddleOCR/start.sh"]'
        environmentVariables:
          testEnv: true
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*